-- JOHANN AUTH v1: only run against a NEW test D1 database first.
CREATE TABLE IF NOT EXISTS auth_users(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE COLLATE NOCASE,created_at INTEGER NOT NULL,deleted_at INTEGER);
CREATE TABLE IF NOT EXISTS auth_codes(id TEXT PRIMARY KEY,email TEXT NOT NULL COLLATE NOCASE,code_hash TEXT NOT NULL,expires_at INTEGER NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,used_at INTEGER);
CREATE INDEX IF NOT EXISTS auth_codes_email ON auth_codes(email,created_at);
CREATE TABLE IF NOT EXISTS auth_sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES auth_users(id) ON DELETE CASCADE,expires_at INTEGER NOT NULL,created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS auth_sessions_user ON auth_sessions(user_id);
CREATE TABLE IF NOT EXISTS auth_vault(user_id TEXT PRIMARY KEY REFERENCES auth_users(id) ON DELETE CASCADE,salt TEXT NOT NULL,iv TEXT NOT NULL,ciphertext TEXT NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS auth_limits(id TEXT PRIMARY KEY,count INTEGER NOT NULL,reset_at INTEGER NOT NULL);
